version: '3.8'

services:
  frontend:
    build:
      context: ./harpyfrontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - harpy-network

  backend:
    build:
      context: ./harpybackend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./harpybackend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - harpy-network

networks:
  harpy-network:
    driver: bridge
